server:
  port: 5001

influxdb:
    server:
        host: localhost
        port: 8086
        dbname: influxdb
        username: root
        password: root
        retentionPolicy: default

spring:
    application:
        name: influxdb-database-handler

eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
        enabled: true


